import { defineConfig, devices } from '@playwright/test';
import 'dotenv/config';

export default defineConfig({
  testDir: './tests',
  // One worker keeps the recording easy to follow.
  workers: 1,
  reporter: [
    ['list'],
    ['html', { open: 'never' }],
    ['json', { outputFile: 'test-results/results.json' }],
    [
      'playwright-qa-reporter',
      {
        outputFile: 'playwright-report.html',
        title: 'MediShop — Automation Report',

        branding: {
          companyName: 'Way2Automation',
          footer: 'Generated by the playwright-qa-reporter example suite.',
        },

        jira: {
          baseUrl: 'https://example.atlassian.net/browse/',
        },

        history: {
          enabled: true,
          file: '.playwright-report-history.json',
          maxRuns: 30,
        },

        network: {
          enabled: true,
          includeBodies: true,
          maxBodyBytes: 100_000,
          excludeHosts: ['google-analytics.com'],
        },

        redact: {
          headers: ['x-company-secret'],
          bodyFields: ['creditCard', 'cvv', 'ssn'],
        },

        attachments: {
          embed: true,
          warnAboveMB: 50,
        },

        performance: {
          slowTestMs: 3_000,
        },

        environment: {
          name: 'Demo',
          release: '1.0.0',
          extra: {
            'App URL': 'https://www.way2automation.com/',
          },
        },

        sections: [
          {
            title: 'Release information',
            content: { Release: '2026.09', Sprint: 'Sprint 18' },
          },
        ],
      },
    ],
  ],
  use: {
    // Keep the trailing slash so goto('login.html') stays inside this folder.
    baseURL: 'https://www.way2automation.com/MediShopWebApp/',
    trace: 'retain-on-failure',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
    { name: 'chrome', use: { ...devices['Desktop Chrome'], channel: 'chrome' } },
  ],
  // npm test runs one browser; Google Chrome is available explicitly for recording.
  // Override this selection with --project=chrome when required.
});
